CREATE TABLE IF NOT EXISTS groupe (
	id INT AUTO_INCREMENT,
	nom VARCHAR(128) NOT NULL,
	groupe INT DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(groupe) REFERENCES groupe(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS evenement (
	id INT AUTO_INCREMENT,
	nom VARCHAR(128) NOT NULL,
	lieu VARCHAR(256) DEFAULT NULL,
	note TEXT DEFAULT NULL,
	debut DATETIME NOT NULL,
	fin DATETIME NOT NULL,
	rappel INT DEFAULT NULL,
	groupe INT DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(groupe) REFERENCES groupe(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tache (
	id INT AUTO_INCREMENT,
	nom VARCHAR(128) NOT NULL,
	fini BOOLEAN NOT NULL DEFAULT 0,
	note TEXT DEFAULT NULL,
	echeance DATETIME DEFAULT NULL,
	rappel INT DEFAULT NULL,
	evenement INT DEFAULT NULL,
	groupe INT DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(evenement) REFERENCES evenement(id) ON DELETE CASCADE,
	FOREIGN KEY(groupe) REFERENCES groupe(id) ON DELETE SET NULL
);
