DROP TABLE IF EXISTS agenta.tache;
DROP TABLE IF EXISTS agenta.evenement;
DROP TABLE IF EXISTS agenta.groupe;

DROP DATABASE IF EXISTS agenta;

CREATE DATABASE agenta;

CREATE TABLE agenta.groupe (
	id INT AUTO_INCREMENT,
	nom VARCHAR(128) NOT NULL,
	groupe INT DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(groupe) REFERENCES agenta.groupe(id) ON DELETE SET NULL
) AUTO_INCREMENT=1;

CREATE TABLE agenta.tache (
	id INT AUTO_INCREMENT,
	nom VARCHAR(128) NOT NULL,
	lieu VARCHAR(256) DEFAULT NULL,
	note TEXT DEFAULT NULL,
	debut DATETIME NOT NULL,
	fin DATETIME NOT NULL,
	rappel INT DEFAULT NULL,
	evenement INT DEFAULT NULL,
	groupe INT DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(evenement) REFERENCES agenta.evenement(id) ON DELETE CASCADE,
	FOREIGN KEY(groupe) REFERENCES agenta.groupe(id) ON DELETE SET NULL
) AUTO_INCREMENT=1;

CREATE TABLE agenta.tache (
	id INT AUTO_INCREMENT,
	nom VARCHAR(128) NOT NULL,
	fini BOOLEAN NOT NULL DEFAULT 0,
	note TEXT DEFAULT NULL,
	echeance DATETIME DEFAULT NULL,
	rappel INT DEFAULT NULL,
	evenement INT DEFAULT NULL,
	groupe INT DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(evenement) REFERENCES agenta.evenement(id) ON DELETE CASCADE,
	FOREIGN KEY(groupe) REFERENCES agenta.groupe(id) ON DELETE SET NULL
) AUTO_INCREMENT=1;
